/**
 * Security Sandbox — Docker Environment Generator
 *
 * Generates a complete, ready-to-run docker-compose.yml + supporting files
 * for each detected technology stack. The goal is a FAITHFUL runtime clone
 * of the original site's environment, not just a static HTML copy.
 *
 * Supported environments:
 *   wordpress, wordpress-woocommerce, nextjs, nuxtjs, laravel, symfony,
 *   django, rails, express, gatsby, astro, drupal, joomla, magento,
 *   shopify-clone, static-nginx, php-generic, node-generic, python-generic
 */

import type { EnvironmentType, TechProfile } from "./tech-detector";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GeneratedEnvironment {
  /** Main docker-compose.yml content */
  dockerCompose: string;
  /** Map of filename → content for additional files */
  extraFiles: Record<string, string>;
  /** Human-readable setup instructions */
  readme: string;
  /** Which ports are exposed */
  ports: { host: number; container: number; service: string }[];
  /** Environment variables the user should review */
  envVars: Record<string, string>;
  /** Stack label for display */
  stackLabel: string;
}

// ─── Shared Helpers ───────────────────────────────────────────────────────────

function mockDbPassword() {
  return "SandboxPass_" + Math.random().toString(36).slice(2, 10);
}

function sentinelSyncConfig(sandboxId: number) {
  return JSON.stringify(
    {
      sentinelSandboxId: sandboxId,
      syncEndpoint: "https://ai-control-center.ofshore.dev/api/sandbox/sync",
      note: "Scan results will be synced to your Sentinel account automatically.",
    },
    null,
    2
  );
}

function baseReadme(stackLabel: string, port: number, sandboxId: number): string {
  return `# Security Sandbox — ${stackLabel}

> Generated by Sentinel Security Sandbox
> Sandbox ID: ${sandboxId}

## Quick Start

\`\`\`bash
docker-compose up -d
\`\`\`

Then open: **http://localhost:${port}**

## Security Testing

Run your security tools against **http://localhost:${port}**:

| Tool | Command |
|------|---------|
| OWASP ZAP | \`docker run -t owasp/zap2docker-stable zap-baseline.py -t http://host.docker.internal:${port}\` |
| Nikto | \`docker run --rm sullo/nikto -h http://host.docker.internal:${port}\` |
| Nuclei | \`nuclei -u http://localhost:${port} -t cves/\` |

## Data Anonymization

All PII has been replaced with mock data:
- Emails → \`user@mock-data.test\`
- Phone numbers → \`+48 000 000 000\`
- NIP/PESEL → anonymized patterns
- IBAN → \`PL00 0000 0000 0000 0000 0000 0000\`

## Sentinel Sync

Scan results sync automatically to your account.
Config: \`sentinel-config.json\`

## Stopping

\`\`\`bash
docker-compose down -v
\`\`\`
`;
}

// ─── WordPress ────────────────────────────────────────────────────────────────

function generateWordPress(profile: TechProfile, sandboxId: number, withWoo = false): GeneratedEnvironment {
  const dbPass = mockDbPassword();
  const phpVersion = profile.phpVersion ?? "8.2";
  const phpMajor = phpVersion.split(".").slice(0, 2).join(".");
  const wpVersion = profile.wordpressVersion ?? "latest";
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — WordPress${withWoo ? " + WooCommerce" : ""} ───
# Stack: PHP ${phpMajor} + MySQL 8.0 + WordPress ${wpVersion}
# Sandbox ID: ${sandboxId}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${dbPass}_root"
      MYSQL_DATABASE: wordpress_sandbox
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-import:/docker-entrypoint-initdb.d   # place exported .sql here
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:${wpVersion}-php${phpMajor}-apache
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${port}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: "${dbPass}"
      WORDPRESS_DB_NAME: wordpress_sandbox
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://localhost:${port}');
        define('WP_HOME', 'http://localhost:${port}');
        define('DISALLOW_FILE_EDIT', true);
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads:/var/www/html/wp-content/uploads
      - ./sentinel-wp-config.php:/var/www/html/wp-config-sandbox.php:ro

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wp_user
      PMA_PASSWORD: "${dbPass}"

volumes:
  db_data:
`;

  const wpConfigExtra = `<?php
// Sentinel Sandbox — additional WordPress config
// This file is mounted read-only and loaded by wp-config.php

// Force sandbox URLs
define('WP_SITEURL', 'http://localhost:${port}');
define('WP_HOME', 'http://localhost:${port}');

// Disable external HTTP requests (sandbox isolation)
define('WP_HTTP_BLOCK_EXTERNAL', false); // set true for full isolation

// Enable debug logging
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

// Disable automatic updates in sandbox
define('AUTOMATIC_UPDATER_DISABLED', true);
define('DISALLOW_FILE_MODS', false); // allow plugin installs for testing
`;

  const sqlImportReadme = `# SQL Import

Place your exported WordPress database dump here as \`dump.sql\`.

## How to export from production:

\`\`\`bash
# Via WP-CLI (recommended)
wp db export dump.sql --allow-root

# Via mysqldump
mysqldump -u root -p wordpress_db > dump.sql
\`\`\`

## After placing dump.sql, run:
\`\`\`bash
docker-compose down -v && docker-compose up -d
\`\`\`

The database will be automatically imported on first start.
`;

  return {
    dockerCompose,
    extraFiles: {
      "sentinel-wp-config.php": wpConfigExtra,
      "sql-import/README.md": sqlImportReadme,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`WordPress${withWoo ? " + WooCommerce" : ""} (PHP ${phpMajor})`, port, sandboxId),
    ports: [
      { host: port, container: 80, service: "WordPress" },
      { host: 8081, container: 80, service: "phpMyAdmin" },
    ],
    envVars: {
      WORDPRESS_DB_PASSWORD: dbPass,
      MYSQL_ROOT_PASSWORD: `${dbPass}_root`,
    },
    stackLabel: `WordPress${withWoo ? " + WooCommerce" : ""} PHP ${phpMajor}`,
  };
}

// ─── Next.js ──────────────────────────────────────────────────────────────────

function generateNextJs(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const nodeVersion = profile.nodeVersion ?? "20";
  const port = 3000;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Next.js ───
# Stack: Node.js ${nodeVersion} + Next.js
# Sandbox ID: ${sandboxId}

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${port}:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SANDBOX_MODE: "true"
      # Add your env vars below (from .env.local of original site)
      # DATABASE_URL: ...
      # NEXTAUTH_SECRET: sandbox-secret-not-for-production
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
`;

  const dockerfile = `FROM node:${nodeVersion}-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Build
RUN npm run build 2>/dev/null || echo "Build failed, running in dev mode"

EXPOSE 3000

# Try production first, fall back to dev
CMD npm start 2>/dev/null || npm run dev
`;

  const appReadme = `# Next.js App Source

Place your Next.js project files here.

## Steps:
1. Copy your Next.js project into this \`app/\` directory
2. Create \`app/.env.local\` with mock environment variables
3. Run: \`docker-compose up -d\`

## Mock .env.local template:
\`\`\`
DATABASE_URL=postgresql://user:password@localhost:5432/sandbox_db
NEXTAUTH_SECRET=sandbox-secret-not-for-production
NEXTAUTH_URL=http://localhost:${port}
NEXT_PUBLIC_API_URL=http://localhost:${port}/api
\`\`\`
`;

  return {
    dockerCompose,
    extraFiles: {
      "app/Dockerfile": dockerfile,
      "app/README.md": appReadme,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Next.js (Node ${nodeVersion})`, port, sandboxId),
    ports: [{ host: port, container: 3000, service: "Next.js App" }],
    envVars: { NODE_ENV: "development" },
    stackLabel: `Next.js Node ${nodeVersion}`,
  };
}

// ─── Nuxt.js ──────────────────────────────────────────────────────────────────

function generateNuxtJs(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const nodeVersion = profile.nodeVersion ?? "20";
  const port = 3000;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Nuxt.js ───
# Stack: Node.js ${nodeVersion} + Nuxt.js
# Sandbox ID: ${sandboxId}

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${port}:3000"
    environment:
      NODE_ENV: development
      NUXT_PUBLIC_SANDBOX: "true"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.nuxt
`;

  const dockerfile = `FROM node:${nodeVersion}-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 2>/dev/null || echo "Build step skipped"
EXPOSE 3000
CMD npm start 2>/dev/null || npm run dev
`;

  return {
    dockerCompose,
    extraFiles: {
      "app/Dockerfile": dockerfile,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Nuxt.js (Node ${nodeVersion})`, port, sandboxId),
    ports: [{ host: port, container: 3000, service: "Nuxt.js App" }],
    envVars: { NODE_ENV: "development" },
    stackLabel: `Nuxt.js Node ${nodeVersion}`,
  };
}

// ─── Laravel ──────────────────────────────────────────────────────────────────

function generateLaravel(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const phpVersion = profile.phpVersion ?? "8.2";
  const phpMajor = phpVersion.split(".").slice(0, 2).join(".");
  const dbPass = mockDbPassword();
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Laravel ───
# Stack: PHP ${phpMajor} + MySQL 8.0 + Laravel
# Sandbox ID: ${sandboxId}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${dbPass}_root"
      MYSQL_DATABASE: laravel_sandbox
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-import:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${port}:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:sandbox_key_replace_with_php_artisan_key_generate
      APP_URL: http://localhost:${port}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_sandbox
      DB_USERNAME: laravel_user
      DB_PASSWORD: "${dbPass}"
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./app:/var/www/html
      - /var/www/html/vendor

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: "${dbPass}"

volumes:
  db_data:
`;

  const dockerfile = `FROM php:${phpMajor}-apache

# Install PHP extensions
RUN apt-get update && apt-get install -y \\
    git curl zip unzip libzip-dev libpng-dev libonig-dev libxml2-dev \\
    && docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Apache config
RUN echo '<VirtualHost *:80>\\n\\
    DocumentRoot /var/www/html/public\\n\\
    <Directory /var/www/html/public>\\n\\
        AllowOverride All\\n\\
        Require all granted\\n\\
    </Directory>\\n\\
</VirtualHost>' > /etc/apache2/sites-available/000-default.conf \\
    && a2enmod rewrite

EXPOSE 80

CMD ["apache2-foreground"]
`;

  return {
    dockerCompose,
    extraFiles: {
      "app/Dockerfile": dockerfile,
      "sql-import/README.md": "Place your Laravel database dump here as dump.sql",
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Laravel (PHP ${phpMajor})`, port, sandboxId),
    ports: [
      { host: port, container: 80, service: "Laravel App" },
      { host: 8081, container: 80, service: "phpMyAdmin" },
    ],
    envVars: { DB_PASSWORD: dbPass },
    stackLabel: `Laravel PHP ${phpMajor}`,
  };
}

// ─── Django ───────────────────────────────────────────────────────────────────

function generateDjango(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const pythonVersion = profile.pythonVersion ?? "3.11";
  const dbPass = mockDbPassword();
  const port = 8000;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Django ───
# Stack: Python ${pythonVersion} + PostgreSQL 15
# Sandbox ID: ${sandboxId}

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: django_sandbox
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user"]
      interval: 10s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${port}:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "sandbox-secret-key-not-for-production"
      DATABASE_URL: "postgresql://django_user:${dbPass}@db:5432/django_sandbox"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
    volumes:
      - ./app:/app

volumes:
  db_data:
`;

  const dockerfile = `FROM python:${pythonVersion}-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || pip install django psycopg2-binary dj-database-url

COPY . .

RUN python manage.py collectstatic --noinput 2>/dev/null || true

EXPOSE 8000

CMD python manage.py migrate --run-syncdb 2>/dev/null; python manage.py runserver 0.0.0.0:8000
`;

  return {
    dockerCompose,
    extraFiles: {
      "app/Dockerfile": dockerfile,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Django (Python ${pythonVersion})`, port, sandboxId),
    ports: [{ host: port, container: 8000, service: "Django App" }],
    envVars: { DATABASE_URL: `postgresql://django_user:${dbPass}@localhost:5432/django_sandbox` },
    stackLabel: `Django Python ${pythonVersion}`,
  };
}

// ─── Ruby on Rails ────────────────────────────────────────────────────────────

function generateRails(sandboxId: number): GeneratedEnvironment {
  const dbPass = mockDbPassword();
  const port = 3000;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Ruby on Rails ───
# Stack: Ruby 3.2 + PostgreSQL 15
# Sandbox ID: ${sandboxId}

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rails_sandbox
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rails_user"]
      interval: 10s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${port}:3000"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: "sandbox_secret_key_base_not_for_production"
      DATABASE_URL: "postgresql://rails_user:${dbPass}@db:5432/rails_sandbox"
    volumes:
      - ./app:/app
      - /app/vendor/bundle

volumes:
  db_data:
`;

  const dockerfile = `FROM ruby:3.2-slim

RUN apt-get update && apt-get install -y build-essential libpq-dev nodejs yarn && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile* ./
RUN bundle install 2>/dev/null || gem install rails

COPY . .

RUN bundle exec rails assets:precompile 2>/dev/null || true

EXPOSE 3000

CMD bundle exec rails db:migrate 2>/dev/null; bundle exec rails server -b 0.0.0.0
`;

  return {
    dockerCompose,
    extraFiles: {
      "app/Dockerfile": dockerfile,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme("Ruby on Rails", port, sandboxId),
    ports: [{ host: port, container: 3000, service: "Rails App" }],
    envVars: { DATABASE_URL: `postgresql://rails_user:${dbPass}@localhost:5432/rails_sandbox` },
    stackLabel: "Ruby on Rails 3.2",
  };
}

// ─── Symfony ──────────────────────────────────────────────────────────────────

function generateSymfony(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const phpVersion = profile.phpVersion ?? "8.2";
  const phpMajor = phpVersion.split(".").slice(0, 2).join(".");
  const dbPass = mockDbPassword();
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Symfony ───
# Stack: PHP ${phpMajor} + PostgreSQL 15
# Sandbox ID: ${sandboxId}

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: symfony_sandbox
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${port}:80"
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: "postgresql://symfony_user:${dbPass}@db:5432/symfony_sandbox?serverVersion=15&charset=utf8"
    volumes:
      - ./app:/var/www/html

volumes:
  db_data:
`;

  const dockerfile = `FROM php:${phpMajor}-apache
RUN apt-get update && apt-get install -y git zip unzip libpq-dev libzip-dev \\
    && docker-php-ext-install pdo pdo_pgsql zip
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
RUN echo '<VirtualHost *:80>\\n    DocumentRoot /var/www/html/public\\n    <Directory /var/www/html/public>\\n        AllowOverride All\\n        Require all granted\\n    </Directory>\\n</VirtualHost>' > /etc/apache2/sites-available/000-default.conf && a2enmod rewrite
EXPOSE 80
CMD ["apache2-foreground"]
`;

  return {
    dockerCompose,
    extraFiles: {
      "app/Dockerfile": dockerfile,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Symfony (PHP ${phpMajor})`, port, sandboxId),
    ports: [{ host: port, container: 80, service: "Symfony App" }],
    envVars: { DATABASE_URL: `postgresql://symfony_user:${dbPass}@localhost:5432/symfony_sandbox` },
    stackLabel: `Symfony PHP ${phpMajor}`,
  };
}

// ─── Drupal ───────────────────────────────────────────────────────────────────

function generateDrupal(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const phpVersion = profile.phpVersion ?? "8.2";
  const phpMajor = phpVersion.split(".").slice(0, 2).join(".");
  const dbPass = mockDbPassword();
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Drupal ───
# Stack: PHP ${phpMajor} + MySQL 8.0 + Drupal
# Sandbox ID: ${sandboxId}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${dbPass}_root"
      MYSQL_DATABASE: drupal_sandbox
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-import:/docker-entrypoint-initdb.d

  drupal:
    image: drupal:10-php${phpMajor}-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${port}:80"
    environment:
      DRUPAL_DATABASE_HOST: db
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal_sandbox
      DRUPAL_DATABASE_USERNAME: drupal_user
      DRUPAL_DATABASE_PASSWORD: "${dbPass}"
    volumes:
      - ./drupal-modules:/var/www/html/modules/custom
      - ./drupal-themes:/var/www/html/themes/custom
      - ./drupal-files:/var/www/html/sites/default/files

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: drupal_user
      PMA_PASSWORD: "${dbPass}"

volumes:
  db_data:
`;

  return {
    dockerCompose,
    extraFiles: {
      "sql-import/README.md": "Place Drupal database dump here as dump.sql",
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Drupal (PHP ${phpMajor})`, port, sandboxId),
    ports: [
      { host: port, container: 80, service: "Drupal" },
      { host: 8081, container: 80, service: "phpMyAdmin" },
    ],
    envVars: { DRUPAL_DATABASE_PASSWORD: dbPass },
    stackLabel: `Drupal PHP ${phpMajor}`,
  };
}

// ─── Magento ──────────────────────────────────────────────────────────────────

function generateMagento(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const phpVersion = profile.phpVersion ?? "8.2";
  const phpMajor = phpVersion.split(".").slice(0, 2).join(".");
  const dbPass = mockDbPassword();
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Magento 2 ───
# Stack: PHP ${phpMajor} + MySQL 8.0 + Elasticsearch + Redis
# Sandbox ID: ${sandboxId}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${dbPass}_root"
      MYSQL_DATABASE: magento_sandbox
      MYSQL_USER: magento_user
      MYSQL_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-import:/docker-entrypoint-initdb.d

  elasticsearch:
    image: elasticsearch:7.17.9
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  app:
    image: bitnami/magento:2
    restart: unless-stopped
    depends_on:
      - db
      - elasticsearch
      - redis
    ports:
      - "${port}:8080"
    environment:
      MAGENTO_DATABASE_HOST: db
      MAGENTO_DATABASE_NAME: magento_sandbox
      MAGENTO_DATABASE_USER: magento_user
      MAGENTO_DATABASE_PASSWORD: "${dbPass}"
      ELASTICSEARCH_HOST: elasticsearch
      MAGENTO_MODE: developer
    volumes:
      - ./magento-app:/bitnami/magento

volumes:
  db_data:
  es_data:
`;

  return {
    dockerCompose,
    extraFiles: {
      "sql-import/README.md": "Place Magento database dump here as dump.sql",
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`Magento 2 (PHP ${phpMajor})`, port, sandboxId),
    ports: [{ host: port, container: 8080, service: "Magento" }],
    envVars: { MAGENTO_DATABASE_PASSWORD: dbPass },
    stackLabel: `Magento 2 PHP ${phpMajor}`,
  };
}

// ─── Static / Generic ─────────────────────────────────────────────────────────

function generateStaticNginx(sandboxId: number): GeneratedEnvironment {
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — Static Site (nginx) ───
# Sandbox ID: ${sandboxId}

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${port}:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
`;

  const nginxConf = `server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Security headers for testing
    add_header X-Sandbox-Mode "sentinel-security-test" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Expose .git for testing (sandbox only!)
    location ~ /\\.git {
        allow all;
    }
}
`;

  return {
    dockerCompose,
    extraFiles: {
      "nginx.conf": nginxConf,
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme("Static Site (nginx)", port, sandboxId),
    ports: [{ host: port, container: 80, service: "nginx" }],
    envVars: {},
    stackLabel: "Static Site (nginx)",
  };
}

function generatePhpGeneric(profile: TechProfile, sandboxId: number): GeneratedEnvironment {
  const phpVersion = profile.phpVersion ?? "8.2";
  const phpMajor = phpVersion.split(".").slice(0, 2).join(".");
  const dbPass = mockDbPassword();
  const port = 8080;

  const dockerCompose = `version: "3.8"

# ─── Sentinel Security Sandbox — PHP Generic ───
# Stack: PHP ${phpMajor} + MySQL 8.0
# Sandbox ID: ${sandboxId}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${dbPass}_root"
      MYSQL_DATABASE: app_sandbox
      MYSQL_USER: app_user
      MYSQL_PASSWORD: "${dbPass}"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-import:/docker-entrypoint-initdb.d

  app:
    image: php:${phpMajor}-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${port}:80"
    volumes:
      - ./site:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: app_user
      PMA_PASSWORD: "${dbPass}"

volumes:
  db_data:
`;

  return {
    dockerCompose,
    extraFiles: {
      "sql-import/README.md": "Place database dump here as dump.sql",
      "sentinel-config.json": sentinelSyncConfig(sandboxId),
    },
    readme: baseReadme(`PHP ${phpMajor} Application`, port, sandboxId),
    ports: [
      { host: port, container: 80, service: "PHP App" },
      { host: 8081, container: 80, service: "phpMyAdmin" },
    ],
    envVars: { DB_PASSWORD: dbPass },
    stackLabel: `PHP ${phpMajor} Generic`,
  };
}

// ─── Main Generator ───────────────────────────────────────────────────────────

export function generateEnvironment(
  profile: TechProfile,
  sandboxId: number
): GeneratedEnvironment {
  switch (profile.environmentType) {
    case "wordpress":
      return generateWordPress(profile, sandboxId, false);
    case "wordpress-woocommerce":
      return generateWordPress(profile, sandboxId, true);
    case "nextjs":
      return generateNextJs(profile, sandboxId);
    case "nuxtjs":
      return generateNuxtJs(profile, sandboxId);
    case "laravel":
      return generateLaravel(profile, sandboxId);
    case "symfony":
      return generateSymfony(profile, sandboxId);
    case "django":
      return generateDjango(profile, sandboxId);
    case "rails":
      return generateRails(sandboxId);
    case "drupal":
      return generateDrupal(profile, sandboxId);
    case "magento":
      return generateMagento(profile, sandboxId);
    case "gatsby":
    case "astro":
    case "node-generic":
      return generateNextJs(profile, sandboxId); // Node-based, same pattern
    case "php-generic":
      return generatePhpGeneric(profile, sandboxId);
    case "joomla":
      return generatePhpGeneric(profile, sandboxId); // Joomla uses PHP+MySQL
    case "shopify-clone":
    case "static-nginx":
    default:
      return generateStaticNginx(sandboxId);
  }
}

/** Returns a human-readable summary of what will be generated */
export function describeEnvironment(profile: TechProfile): string {
  const env = profile.environmentType;
  const techs = profile.detectedTechs.map((t) => `${t.name}${t.version ? ` ${t.version}` : ""} (${t.confidence}%)`).join(", ");

  return [
    `Environment: **${env}**`,
    `Detected technologies: ${techs || "none"}`,
    `Detection confidence: ${profile.confidence}%`,
    ...(profile.notes.length > 0 ? [`Notes: ${profile.notes.join("; ")}`] : []),
  ].join("\n");
}
